CREATE VIEW wycieczki_osoby
 AS
 SELECT
 w.ID_WYCIECZKI,
 w.NAZWA,
 w.KRAJ,
 w.DATA,
 o.IMIE,
 o.NAZWISKO,
 r.STATUS
 FROM WYCIECZKI w
 JOIN REZERWACJE r ON w.ID_WYCIECZKI = r.ID_WYCIECZKI
 JOIN OSOBY o ON r.ID_OSOBY = o.ID_OSOBY;

CREATE VIEW wycieczki_osoby_potwierdzone
 AS
 SELECT
 w.ID_WYCIECZKI,
 w.NAZWA,
 w.KRAJ,
 w.DATA,
 o.IMIE,
 o.NAZWISKO,
 r.STATUS
 FROM WYCIECZKI w
    JOIN REZERWACJE r ON w.ID_WYCIECZKI = r.ID_WYCIECZKI
    JOIN OSOBY o ON r.ID_OSOBY = o.ID_OSOBY
 WHERE r.STATUS = 'P' OR r.STATUS = 'Z';

CREATE VIEW wycieczki_przyszle
 AS
 SELECT
 w.ID_WYCIECZKI,
 w.NAZWA,
 w.KRAJ,
 w.DATA,
 o.IMIE,
 o.NAZWISKO,
 r.STATUS
 FROM WYCIECZKI w
    JOIN REZERWACJE r ON w.ID_WYCIECZKI = r.ID_WYCIECZKI
    JOIN OSOBY o ON r.ID_OSOBY = o.ID_OSOBY
 WHERE w.DATA > SYSDATE;

CREATE VIEW wycieczki_miejsca
 AS
 SELECT 
 r.ID_WYCIECZKI, 
 w.NAZWA, 
 w.KRAJ, 
 w.DATA, 
 w.LICZBA_MIEJSC, 
 w.LICZBA_MIEJSC - COUNT(r.ID_WYCIECZKI) AS LICZBA_WOLNYCH_MIEJSC
FROM REZERWACJE r
    JOIN WYCIECZKI w ON r.ID_WYCIECZKI = w.ID_WYCIECZKI
WHERE r.STATUS != 'A'
GROUP BY r.ID_WYCIECZKI, w.KRAJ, w.LICZBA_MIEJSC, w.NAZWA, w.DATA
ORDER BY r.ID_WYCIECZKI;
 
create view DOSTEPNE_WYCIECZKI
AS
SELECT 
 KRAJ, 
 DATA, 
 NAZWA, 
 LICZBA_MIEJSC, 
 ID_WYCIECZKI
FROM WYCIECZKI_MIEJSCA
  WHERE LICZBA_WOLNYCH_MIEJSC > 0 AND DATA >SYSDATE;


CREATE view rezerwacje_do_anulowania
AS
SELECT
 r.NR_REZERWACJI,
 r.ID_WYCIECZKI,
 r.ID_OSOBY,
 w.NAZWA,
 w.DATA
FROM REZERWACJE r
 JOIN wycieczki w ON r.ID_WYCIECZKI = w.ID_WYCIECZKI
 WHERE r.STATUS = 'N' and w.DATA + 7 > SYSDATE;

SELECT * FROM WYCIECZKI_OSOBY;
SELECT * FROM WYCIECZKI_OSOBY_POTWIERDZONE;
SELECT * FROM WYCIECZKI_PRZYSZLE;
SELECT * FROM WYCIECZKI_MIEJSCA;
SELECT * FROM DOSTEPNE_WYCIECZKI;
SELECT * FROM REZERWACJE_DO_ANULOWANIA;